# Generated by Django 6.0 on 2025-12-14 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledVaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('notified', models.BooleanField(default=False)),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mom.mother')),
                ('vaccination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mom.vaccination')),
            ],
        ),
    ]
