# Generated by Django 6.0 on 2025-12-16 06:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mom', '0002_scheduledvaccination'),
    ]

    operations = [
        migrations.RenameField(
            model_name='childvaccination',
            old_name='reminder_sent',
            new_name='reminder_day_before_sent',
        ),
        migrations.AddField(
            model_name='childvaccination',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='childvaccination',
            name='reminder_on_day_sent',
            field=models.BooleanField(default=False),
        ),
    ]
