# Generated by Django 6.0 on 2025-12-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mom', '0003_rename_reminder_sent_childvaccination_reminder_day_before_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregnancy',
            name='notes',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
