# Generated by Django 6.0 on 2025-12-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mom', '0004_pregnancy_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='childvaccination',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
